version: '3.8'

services:
  seu-servico:
    image: ghcr.io/seu-usuario/seu-servico:latest

    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=200

    env_file:
      - .env

    networks:
      - traefik_public
      - app_internal

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider",
             "http://localhost:8080/seu-app/actuator/health"]
      interval: 15s
      timeout: 10s
      start_period: 40s    # Spring Boot leva ~35s para iniciar em ARM64
      retries: 3

    deploy:
      mode: replicated
      replicas: 1

      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G

      labels:
        # Traefik routing
        - traefik.enable=true
        - traefik.http.routers.seu-app.rule=Host(`api.seudominio.com`)
        - traefik.http.routers.seu-app.entrypoints=websecure
        - traefik.http.routers.seu-app.tls.certresolver=letsencrypt
        - traefik.http.services.seu-app.loadbalancer.server.port=8080
        - traefik.docker.network=traefik_public

        # Segurança (opcional - descomentar se quiser)
        # - traefik.http.routers.seu-app.middlewares=global-api-security@swarm

        # Health check
        - traefik.http.services.seu-app.loadbalancer.healthcheck.path=/seu-app/actuator/health
        - traefik.http.services.seu-app.loadbalancer.healthcheck.interval=15s

networks:
  traefik_public:
    external: true
  app_internal:
    driver: overlay
    attachable: true
